In [1]:
import numpy as np

# 1. Initialize an empty array with size 2x2.
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):")
print(empty_array)

# 2. Initialize an all-ones array with size 4x2.
ones_array = np.ones((4, 2))
print("\n2. All-Ones Array (4x2):")
print(ones_array)

# 3. Return a new array of given shape and type, filled with a fill value.
# Example shape (3, 3) and fill value 7.
fill_array = np.full((3, 3), 7)
print("\n3. Array filled with value 7 (3x3):")
print(fill_array)

# 4. Return a new array of zeros with the same shape and type as a given array.
# Example given array
example_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(example_array)
print("\n4. Array of zeros with same shape as example array:")
print(zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array.
ones_like_array = np.ones_like(example_array)
print("\n5. Array of ones with same shape as example array:")
print(ones_like_array)

# 6. Convert an existing list to a NumPy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. NumPy Array converted from list:")
print(numpy_array)


1. Empty Array (2x2):
[[6.89800058e-307 6.89799040e-307]
 [2.33646676e-307 1.76127852e-312]]

2. All-Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Array of zeros with same shape as example array:
[[0 0]
 [0 0]]

5. Array of ones with same shape as example array:
[[1 1]
 [1 1]]

6. NumPy Array converted from list:
[1 2 3 4]


In [2]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49.
array_10_49 = np.arange(10, 50)
print("1. Array with values from 10 to 49:")
print(array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_0_8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix with values from 0 to 8:")
print(matrix_0_8)

# 3. Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\n4. Random Array of size 30 and its mean:")
print(random_array_30)
print("Mean:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print("\n5. 10x10 Random Matrix, Min and Max values:")
print(random_matrix_10x10)
print("Min Value:", min_value)
print("Max Value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print("\n6. Zero array with 5th element replaced by 1:")
print(zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\n7. Reversed Array:")
print(reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside.
border_array = np.ones((5, 5))  # Example size 5x5
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1 on border and 0 inside:")
print(border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1  # Odd rows
checkerboard_matrix[::2, 1::2] = 1  # Even rows
print("\n9. 8x8 Checkerboard Pattern Matrix:")
print(checkerboard_matrix)


1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array of size 30 and its mean:
[0.90044696 0.39130757 0.05805306 0.86848672 0.84413722 0.22253974
 0.67678839 0.29311736 0.0227536  0.33522412 0.15764545 0.53029778
 0.41370159 0.19166845 0.89190892 0.94941259 0.10925955 0.3886463
 0.15668642 0.54001108 0.16917605 0.09205097 0.10893957 0.25428637
 0.88744137 0.78207028 0.68301476 0.68638632 0.61666333 0.69037325]
Mean: 0.4637498389192724

5. 10x10 Random Matrix, Min and Max values:
[[0.97137552 0.88286606 0.7861318  0.92944892 0.39349683 0.03983555
  0.84869585 0.56731247 0.03931459 0.08800856]
 [0.38145585 0.29095796 0.5475014  0.19921681 0.65847402 0.6437981
  0.62787039 0.02904125 0.83238692 0.58874508]
 [0.34666111 0.5155329  0.01099542 

In [3]:
import numpy as np

# Define the given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (x and y)
array_add = x + y
print("1. Addition of x and y:")
print(array_add)

# 2. Subtract the two arrays (x and y)
array_subtract = x - y
print("\n2. Subtraction of x and y:")
print(array_subtract)

# 3. Multiply the array (x) with an integer (e.g., 2)
array_multiply = x * 2
print("\n3. Multiplication of x by 2:")
print(array_multiply)

# 4. Find the square of each element in the array (x)
array_square = np.square(x)
print("\n4. Square of each element in x:")
print(array_square)

# 5. Find the dot product
dot_v_w = np.dot(v, w)  # v . w
dot_x_v = np.dot(x, v)  # x . v
dot_x_y = np.dot(x, y)  # x . y
print("\n5. Dot products:")
print(f"v . w = {dot_v_w}")
print(f"x . v = {dot_x_v}")
print(f"x . y =\n{dot_x_y}")

# 6. Concatenate x and y along rows, and v and w along columns
concat_xy_rows = np.concatenate((x, y), axis=0)  # Row-wise for 2D
concat_vw_columns = np.vstack((v, w))  # Column-wise for 1D
print("\n6. Concatenation:")
print("Concatenate x and y along rows:")
print(concat_xy_rows)
print("Concatenate v and w along columns:")
print(concat_vw_columns)

# 7. Attempt to concatenate x and v
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\n7. Concatenate x and v:")
    print(concat_x_v)
except ValueError as e:
    print("\n7. Concatenate x and v raised an error:")
    print(e)
    print("Explanation: The shapes of x (2x2) and v (1x2) do not align for concatenation along axis 0. "
          "To fix this, v must be reshaped to a 2D array of shape (2, 2) or compatible shape.")

# Optional fix for task 7 (reshaping v to make it compatible)
v_reshaped = v.reshape(1, -1)  # Reshape to 2D
concat_x_v_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\n7. Fixed Concatenate x and reshaped v:")
print(concat_x_v_fixed)


1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of x by 2:
[[ 2  4]
 [ 6 10]]

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
v . w = 219
x . v = [29 77]
x . y =
[[19 22]
 [50 58]]

6. Concatenation:
Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 10]
 [11 12]]

7. Concatenate x and v raised an error:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The shapes of x (2x2) and v (1x2) do not align for concatenation along axis 0. To fix this, v must be reshaped to a 2D array of shape (2, 2) or compatible shape.

7. Fixed Concatenate x and reshaped v:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


In [4]:
#A.A^-1
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute A * A^-1
A_inverse = np.linalg.inv(A)  # Inverse of A
identity_matrix = np.dot(A, A_inverse)  # A * A^-1

print("1. A * A^-1 = I (Identity Matrix):")
print(identity_matrix)
# Check if the result is approximately the identity matrix
print("Is approximately identity matrix:", np.allclose(identity_matrix, np.eye(2)))


1. A * A^-1 = I (Identity Matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is approximately identity matrix: True


In [5]:
# AB != BA
# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. AB ≠ BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)
print("AB and BA are not equal:", not np.array_equal(AB, BA))



2. AB ≠ BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
AB and BA are not equal: True


In [6]:
#(AB)^T = B^T.A^T
# Compute (AB)^T and B^T A^T
AB_transpose = np.transpose(np.dot(A, B))
BT_AT = np.dot(B.T, A.T)

print("\n3. (AB)^T = B^T A^T:")
print("(AB)^T:")
print(AB_transpose)
print("B^T A^T:")
print(BT_AT)
print("Are equal:", np.allclose(AB_transpose, BT_AT))



3. (AB)^T = B^T A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]
Are equal: True


In [7]:
#system of linear equation: X=A^-1.B
# Define matrices A and B for the system of equations
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using the inverse method
A_eq_inverse = np.linalg.inv(A_eq)
X = np.dot(A_eq_inverse, B_eq)

print("\nSystem of Linear Equations Solution using Inverse Method:")
print("Solution for X (x, y, z):")
print(X)



System of Linear Equations Solution using Inverse Method:
Solution for X (x, y, z):
[ 2.  1. -2.]


In [8]:
# Solve using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)

print("\nSystem of Linear Equations Solution using np.linalg.solve:")
print("Solution for X (x, y, z):")
print(X_solve)



System of Linear Equations Solution using np.linalg.solve:
Solution for X (x, y, z):
[ 2.  1. -2.]


In [ ]:
import numpy as np
import time

# Helper function to measure execution time
def measure_time(func, *args):
    start_time = time.time()
    result = func(*args)
    end_time = time.time()
    return result, end_time - start_time

# 1. Element-wise Addition
# Python Lists
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

def python_addition(a, b):
    return [a[i] + b[i] for i in range(len(a))]

_, time_python_add = measure_time(python_addition, list1, list2)

# NumPy Arrays
array1 = np.array(list1)
array2 = np.array(list2)

def numpy_addition(a, b):
    return a + b

_, time_numpy_add = measure_time(numpy_addition, array1, array2)

print(f"1. Element-wise Addition:")
print(f"Python Lists: {time_python_add:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_add:.6f} seconds\n")

# 2. Element-wise Multiplication
# Python Lists
def python_multiplication(a, b):
    return [a[i] * b[i] for i in range(len(a))]

_, time_python_mul = measure_time(python_multiplication, list1, list2)

# NumPy Arrays
def numpy_multiplication(a, b):
    return a * b

_, time_numpy_mul = measure_time(numpy_multiplication, array1, array2)

print(f"2. Element-wise Multiplication:")
print(f"Python Lists: {time_python_mul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_mul:.6f} seconds\n")

# 3. Dot Product
# Python Lists
def python_dot_product(a, b):
    return sum(a[i] * b[i] for i in range(len(a)))

_, time_python_dot = measure_time(python_dot_product, list1, list2)

# NumPy Arrays
def numpy_dot_product(a, b):
    return np.dot(a, b)

_, time_numpy_dot = measure_time(numpy_dot_product, array1, array2)

print(f"3. Dot Product:")
print(f"Python Lists: {time_python_dot:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_dot:.6f} seconds\n")

# 4. Matrix Multiplication
# Python Lists
matrix1 = [[i for i in range(1000)] for _ in range(1000)]
matrix2 = [[i for i in range(1000)] for _ in range(1000)]

def python_matrix_multiplication(a, b):
    result = [[sum(a[i][k] * b[k][j] for k in range(len(b))) for j in range(len(b[0]))] for i in range(len(a))]
    return result

_, time_python_matmul = measure_time(python_matrix_multiplication, matrix1, matrix2)

# NumPy Arrays
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

def numpy_matrix_multiplication(a, b):
    return np.dot(a, b)

_, time_numpy_matmul = measure_time(numpy_matrix_multiplication, matrix1_np, matrix2_np)

print(f"4. Matrix Multiplication (1000x1000):")
print(f"Python Lists: {time_python_matmul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_matmul:.6f} seconds\n")


1. Element-wise Addition:
Python Lists: 0.208616 seconds
NumPy Arrays: 0.006860 seconds

2. Element-wise Multiplication:
Python Lists: 0.225699 seconds
NumPy Arrays: 0.007908 seconds

3. Dot Product:
Python Lists: 0.253214 seconds
NumPy Arrays: 0.003509 seconds

